// Modelos extraídos da pasta OLD - prescricao
// Total: 13 modelos
// Tipos: decisao
// Formatos: ODT
// Data: 2026-01-21T00:41:14.314Z

export const MODELOS_PRESCRICAO_OLD = [
    {
        id: 'old_anula__o_decis_o_prescri__o_odt',
        nome: 'ANULAÇÃO decisão prescrição',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Compulsando os autos, verificou-se que foi declara a pretensão da prescrição executória da pena privativa de liberdade aplicada a EDMILSON SOLON DA SILVA, na decisão de fl. 234, de forma equivocada, pois baseou-se em uma suposta pena unificada de 19 (dezenove) anos e 06 (seis) meses de reclusão.
Adiante, foi certificada a ocorrência de tal equívoco e elencados os processos que compõem a presente execução penal (fl. 235).
Relatados.
De logo, chamo o feito à boa ordem processual para tornar sem qualquer efeito jurídico-processual a sentença proferida na fl. 234, comando decisório que declarou prescrita a pretensão executória da pena privativa de liberdade remanescente nos presentes autos.
Enfim, trata-se de pena aplicada a EDMILSON SOLON DA SILVA, de 05 (cinco) anos e 06 (seis) meses de reclusão, por delito de furto, em regime fechado, sendo recebida novas guias de recolhimento, quais sejam: apenso 1, tratando de condenação a 06 (seis) meses de detenção, por delito capitulado no art. 16 da Lei 6.368/76, em regime aberto, na ação penal de nº 0001323-31.1988.8.20.0001, de origem na 4ª Vara Criminal de Natal; apenso 2, tratando de condenação a 04 (quatro) anos de reclusão, em regime aberto, na ação penal nº 0012651-69.1999.8.20.0001, oriundo da 2ª Vara Criminal da Comarca de Natal; apenso 3, ação penal nº 0014059-95.1999.8.20.0001, tratando de condenação a 03 (três) anos de reclusão, em regime fechado, de origem na 9ª Vara Criminal da Comarca de Natal; apenso 4, tratando de condenação a 04 (quatro) anos e 06 (seis) meses, em regime fechado, na ação penal nº 0000474-39.2000.8.20.0001, origem na 9ª Vara Criminal de Natal; e apenso 5, tratando de condenação a 02 (dois) anos de reclusão, em regime fechado, na ação penal nº 0001665-22.2000.8.20.0001, de origem na 9ª Vara Criminal da Comarca de Natal.
Trata-se, na espécie, de concurso material de delitos, não se podendo ter os crimes como continuação entre si, impondo-se a soma das penas.
Por oportuno, anoto que a data-base para futuros benefícios deve ser a da última prisão ou falta grave.
Isto posto, torno sem qualquer jurídico-processual a sentença proferida à fl. 234, anulando-a, e unifico em 19 (dezenove) anos de reclusão e 06 (seis) meses de detenção a pena privativa de liberdade em execução nestes autos, a ser cumprida em regime fechado face ao saldo de pena e ao determinado em sentenças condenatórias.
P.R.I. Comunique-se ao estabelecimento prisional e expeça-se a competente Guia de Execução Penal unificadora.
Após, retornem-me conclusos para análise de possível prescrição da pretensão executória.`,
    },
    {
        id: 'old_decis_o_extin__o_de_punibilidade_por_prescri__o_executoria_odt',
        nome: 'decisão extinção de punibilidade por prescrição executoria',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Tratam os autos de processo de execução de pena imposta a EDSON PEREIRA ALVES, de  7 (sete) anos, 6 (seis) meses e 21 (vinte e um) dias de reclusão em regime semiaberto, sendo 3 (três) anos, 6 (seis) meses e 21 (vinte e um) dias de reclusão na ação penal de nº 0001359-16.2001.8.20.0002 e 4 (quatro) anos de reclusão na ação penal de nº  0008382-50.2000.8.20.0001, ambos pela prática de delito capitulado no  art. 157, § 2º c/c art. 29  do código Penal.
A sentença condenatória da ação penal de nº 0001359-16.2001.8.20.0002  com a pena de 3 (três) anos, 6 (seis) meses e 21 (vinte e um) dias transitou em julgado para a acusação em 07/12/2006  (ev. 1.1, fl 66v, pág. virtual 67),  e na ação penal de nº 0008382-50.2000.8.20.0001 com a pena de 4 (quatro) anos que transitou em julgado para a acusação em 24/09/2007.
Ademais, o início do cumprimento da pena se deu em 04/02/2019.
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (evento 1.3, pág. virtual 8/9)
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória,  disciplinada no art. 110 do mesmo estatuto.
No caso, foi o réu, condenado a  03 (três) anos, 06 (seis) meses e 21 (vinte e um) dias e 04 (quatro) anos de reclusão, prescrevendo a pretensão executória em 8 (oito) anos cada pena, prazo já transcorrido desde 07/12/2014 e 24/09/2017 ,posto datar a sentença condenatória com trânsito em julgado de 07/12/2006 e 24/09/2007 (Cód.Penal, arts. 109, IV c/c 110 e 112, I).
Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada neste autos a EDSON PEREIRA ALVES, já qualificado nos autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, IV, 110 e 112, todos do Código Penal.
P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.

Natal, 05 de abril de 2019.

Henrique Baltazar Vilar dos Santos
Juiz de Direito`,
    },
    {
        id: 'old_extin__o_punitiva_odt',
        nome: 'extinção punitiva',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Vistos etc.
WEBERTON DE SOUZA XAVIER, requereu, através de advogado, que a punibilidade de dois anos de reclusão pelo crime de porte ilegal de arma de fogo de suo permitido, fosse declarada prescrita, alegando que entre a data do recebimento da denúncia e a publicação da sentença condenatória passaram-se mais de dois anos (fls. 93/94), com o que concordou o Ministério Público (fl. 98). 
Às fls. 101/205 acostou-se sindicância para apurar suposta falta grave.
A defesa, por sua vez, requereu a nulidade do processo administrativo, já que a sindicância foi realizada sem a presença de defensor (fls. 106/107).
É o relatório.
Prescrição é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou executória durante certo lapso de tempo. A primeira, que ocorre antes de transitar em julgado a sentença final, está regulada pelo art. 109 do Código Penal, enquanto a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, tem disciplina no art. 110 do mesmo estatuto.
In casu, o prazo prescricional aplicável à espécie, considerando a pena aplicada, é de quatro anos, nos termos do art. 109, V, do mesmo diploma legal. Todavia, sendo ao tempo do crime o apenado menor de vinte e um anos de idade, de acordo com o art. 115 do Código Penal serão reduzidos pela metade os prazos de prescrição, logo, aqui o prazo prescricional aplicável é de dois anos.
Assim sendo, verifico que entre a data do recebimento da denúncia (21/01/2011) e a prolação da sentença condenatória (02/05/2013) decorreram mais de dois anos, estando consumada a extinção da punibilidade, pela prescrição da pretensão punitiva estatal.
Isto posto, declaro a extinção da punibilidade de dois anos de reclusão pelo crime de porte ilegal de arma de fogo, pela prescrição da pretensão punitiva do Estado, o que faço com arrimo no art. 107, IV, c/c os arts. 109, V, todos do Código Penal e art. 61, do Código Processo Penal, bem como mando desentranhar a execução nº 0102228-18.2015.8.20.0124, ora em apenso, desapensar as folhas nº 100/107 e acostar no precitado processo executório.
P.R.I. Comunique-se à Sétima Vara Criminal e arquivem-se estes autos após o trânsito em julgado, dando-se "baixa" no SAJ. Deixo de mandar expedir alvará de soltura em razão de ordem de prisão decretada em desfavor do apenado pelo Juízo da Primeira Vara Criminal de Parnamirim na execução penal nº 0102451-34.2016.8.20.0124.
Após cumpridas todas as determinações, certifique-se naquela execução onde está recolhido o apenado e expeça-se, nela, guia de execução penal atualizada.
Natal, 08 de agosto de 2016`,
    },
    {
        id: 'old_precri__o___punitiva_odt',
        nome: 'PRECRIÇÃO - punitiva',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Tratam os autos de processo de execução de pena unificada em 10 (dez) anos e 03 (três) meses de reclusão, em regime fechado, por crimes dos arts. 289, §1º, 304 e 297 do CP, fatos ocorridos em 26/06/2000 e 05/08/2013.
A sentença condenatória que impôs pena de 07 (sete) anos e 06 (seis) meses de reclusão (processo n° 0000785-98.2003.4.05.8400) foi publicada em 31/08/2006, cujo acórdão transitou em julgado para ambas as partes em 13/11/2007, enquanto que a sentença da pena de 02 (dois) anos e 09 (nove) meses foi publicada em 17/03/2014, tendo o acórdão transitado em julgado em 02/04/2018 (processo nº 0810994-68.2018.4.05.8400), tendo o apenado sido preso para início do cumprimento das execuções em 18/09/2019.
Ao evento 33, o apenado, por intermédio de seu advogado, juntou petição requerendo o reconhecimento da prescrição da pretensão punitiva das penas, devendo ser declarada a extinção  da punibilidade.
Interveio o Ministério Público opinando pelo indeferimento do pedido (evento 36.1).
Relatados.
De antemão, observo que a defesa aduz excesso no lapso temporal entre o trânsito em julgado para a acusação e o início do cumprimento da sentença, motivo pelo qual deve ser declarada a prescrição. Entretanto, configura-se como causa interruptiva da prescrição a reincidência (art. 117, VI, CP), devendo o prazo começar a correr novamente a partir do dia da interrupção.
No caso em tela, após transitado em julgado o acórdão do primeiro processo (dia 13/11/2007), o apenado cometera novo crime no dia 05/08/2013, originando o processo nº 0810994-68.2018.4.05.8400 e configurando, assim, o instituto da reincidência, reconhecido na sentença condenatória do evento 1.3, pv. 48. 
Desse modo, a reincidência da data 05/08/2013 é o último marco interruptivo. Portanto, passo à análise da prescrição.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão. Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
Observo, contudo, que mesmo na hipótese de unificação de penas, a incidência da pretensão estatal para a execução deve ser feita isoladamente para cada crime. Nesse sentido é a jurisprudência do Superior Tribunal de Justiça:
HABEAS CORPUS. PROCESSO PENAL. FURTO E QUADRILHA. PRESCRIÇÃO DA PRETENSÃO EXECUTÓRIA. INOCORRÊNCIA. ANÁLISE QUE DEVE OCORRER PARA CADA DELITO PRATICADO ISOLADAMENTE.1. A análise da pretensão da prescrição executória deve ser realizada para cada delito praticado isoladamente, inclusive, no caso de concurso de crimes.2. O art. 109, do Código Penal, em seu inciso IV, prescreve o prazo prescricional de 08 (oito) anos tanto para o delito de furto quanto para o de quadrilha, em face da pena concretizada a cada um dos delitos ser superior a 02 (dois) anos e não exceder a 04 (quatro)anos. Ocorre que, na hipótese, aplica-se o art. 110, do Código Penal, pois a sentença condenatória reconheceu a reincidência do Paciente, incidindo, assim, o acréscimo de 1/3 no referido prazo,resultando no prazo prescricional de 10 (dez) anos e 08 (oito) meses.3. Considerando-se como último marco interruptivo da prescrição o dia da interrupção da execução da pena do Paciente, conforme dicção do art. 112, inciso II, do Código Penal, não se caracteriza a extinção da punibilidade pela prescrição da pretensão executória em relação ao crime de quadrilha, uma vez que não transcorreu o lapso temporal superior a 10 (dez) anos e 08 (oito) meses desde o último marco interruptivo.4. Caso se aplique, simultaneamente, o mesmo prazo de prescrição em ambas as penas, como pretende a Defesa, o decurso de tempo necessário à extinção da punibilidade seria desproporcional ao total de pena obtido do concurso de crimes.5. Habeas corpus denegado. (STJ, HC 92069 / RO HABEAS CORPUS 2007/0236368-6 . 2010)
Destarte, relativamente à condenação correspondente ao crime mais grave – cujo cumprimento, portanto, deve se dar em primeiro lugar, a data da reincidência configura-se a data-base sobre a qual deve ser analisada a prescrição punitiva.
No caso, foi o réu, então reincidente e maior de 21 anos, condenado a 04 (quatro) anos e 06 (seis) meses de reclusão quanto ao crime do art. 289, §1º, do CP, no processo n° 0000785-98.2003.4.05.8400, regulando-se a prescrição pela pena aplicada, incidindo, assim, a pretensão executória de doze anos (Código Penal, arts. 109, III).
Entretanto, o referido prazo deve ser aumentado em 1/3 (um terço), em virtude da reincidência do apenado, conforme disciplina o art. 110, "caput", do CP, totalizando, assim, um prazo de dezesseis anos.
Portanto, posto datar a reincidência, último marco interruptivo de 05/08/2013 (art. 117, VI, do CP) e sendo o prazo aplicável de dezesseis anos, depreende-se que este decorrerá somente em 04/08/2029.
Outrossim, quanto à pena de 03 (três) anos de reclusão relativa ao crime do art. 304 do CP no processo nº 0000785-98.2003.4.05.8400, o sentenciado não iniciou o cumprimento, portanto, no caso, a prescrição punitiva regula-se pela pena aplicada, conforme art. 110, do CP, incidindo a pretensão executória de oito anos (Código Penal, arts. 109, IV), aumentada de um terço, alcanaçando-se dez anos e oito meses, prazo esse que decorreria apenas em 04/04/2024. Senão, vejamos:
HABEAS CORPUS. ARTS. 180, § 1º; 311 (DUAS VEZES); E 288, PARÁGRAFO ÚNICO, TODOS DO CÓDIGO PENAL, EM CONCURSO MATERIAL. PRESCRIÇÃO EXECUTÓRIA RELATIVA AO CRIME DE QUADRILHA MAJORADO. INOCORRÊNCIA. ART. 110, DO CÓDIGO PENAL. (...). HABEAS CORPUS PARCIALMENTE CONHECIDO E, NESSA EXTENSÃO, DENEGADO. 1. Após o trânsito em julgado da sentença condenatória, o prazo para a prescrição executória regula-se pelo total de pena aplicada (art. 110, do Código Penal). (…) (HC 238.100/SC, Rel. Ministra LAURITA VAZ, QUINTA TURMA, julgado em 06/08/2013, DJe 13/08/2013) 
Por conseguinte, quanto ao processo nº 0810994-68.2018.4.05.8400, que condenou o réu a uma pena de 02 (dois) anos e 09 (nove) meses, pelo delito capitulado no art. 297 do CP, a publicação do acórdão, qual seja 11/01/2018, caracteriza-se como marco interruptivo da prescrição punitiva, consoante entendimento do STF:
AGRAVO REGIMENTAL NO RECURSOEXTRAORDINÁRIO. PRESCRIÇÃO DA PRETENSÃO PUNITIVA. ACÓRDÃO CONFIRMATÓRIO DE SENTENÇA CONDENATÓRIA. INTERRUPÇÃO DO PRAZO PRESCRICIONAL. POSSIBILIDADE.AUSÊNCIA DE INÉRCIA DO ESTADO. RESPEITO AO DEVIDOPROCESSO LEGAL. (...)  2. Não obstante a posição de parte da doutrina, o Código Penal não faz distinção entre acórdão condenatório inicial e acórdão condenatório confirmatório da decisão. Não há, sistematicamente, justificativa para tratamentos díspares.3. A ideia de prescrição está vinculada à inércia estatal e o que exist ena confirmação da condenação é a atuação do Tribunal.Consequentemente, se o Estado não está inerte, há necessidade de se interromper a prescrição para o cumprimento do devido processo legal. 
Dessa forma, incidirá a pretensão executória de oito anos (Código Penal, arts. 109, IV), acrescido de um terço, resultando em dez anos e oito meses, que transcorreria apenas em 10/03/2045.
Isto posto, em conssonância com o parecer do Ministério Público, não ultrapassado os prazos prescricionais, indefiro o pedido de reconhecimento da prescrição da pena privativa de liberdade executada neste autos.
P.R.I. À Secretaria, em atenção ao parecer do Ministério Público, para oficiar a 3ª Vara Criminal de Natal e a Comarca de Tangará informando a respeito do local de custódia do apenado, conforme certidão ao evento 41.`,
    },
    {
        id: 'old_prescri__o___concurso_material__continuidade_delitiva_odt',
        nome: 'PRESCRIÇÃO - Concurso material- Continuidade delitiva',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO – MAIOR DE 21 – CONCURSO DE CRIMES – CONTINUIDADE DELITIVA

Tratam os autos de processo de execução de pena imposta de 09 (nove) anos e 03 (três) meses de reclusão em regime fechado, pelos crimes dos arts. 180, §1º e 311, “caput”.
A sentença condenatória transitou em julgado para ambas as partes em 11/07/2007.
Anoto que, compulsando os autos nos SEEU, o cadastro da ação penal não fora devidamente alimentado, de modo a considerar o concurso material de crimes; bem como consta inserida uma pena de 10 (dez) anos e 07 (sete) meses. Contudo, a pena correta é de 09 (nove) anos e 03 (três) meses
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão. Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
Observo, contudo, que mesmo na hipótese de concurso material de crimes, a incidência da pretensão estatal para a execução deve ser feita isoladamente para cada crime, conforme preceitua o art. 119, do CP. Nesse sentido é a jurisprudência do Superior Tribunal de Justiça:
HABEAS CORPUS. PROCESSO PENAL. FURTO E QUADRILHA. PRESCRIÇÃO DA PRETENSÃO EXECUTÓRIA. INOCORRÊNCIA. ANÁLISE QUE DEVE OCORRER PARA CADA DELITO PRATICADO ISOLADAMENTE.1. A análise da pretensão da prescrição executória deve ser realizada para cada delito praticado isoladamente, inclusive, no caso de concurso de crimes. 2. O art. 109, do Código Penal, em seu inciso IV, prescreve o prazo prescricional de 08 (oito) anos tanto para o delito de furto quanto para o de quadrilha, em face da pena concretizada a cada um dos delitos ser superior a 02 (dois) anos e não exceder a 04 (quatro)anos. Ocorre que, na hipótese, aplica-se o art. 110, do Código Penal, pois a sentença condenatória reconheceu a reincidência do Paciente, incidindo, assim, o acréscimo de 1/3 no referido prazo,resultando no prazo prescricional de 10 (dez) anos e 08 (oito) meses.3. Considerando-se como último marco interruptivo da prescrição o dia da interrupção da execução da pena do Paciente, conforme dicção do art. 112, inciso II, do Código Penal, não se caracteriza a extinção da punibilidade pela prescrição da pretensão executória em relação ao crime de quadrilha, uma vez que não transcorreu o lapso temporal superior a 10 (dez) anos e 08 (oito) meses desde o último marco interruptivo.4. Caso se aplique, simultaneamente, o mesmo prazo de prescrição em ambas as penas, como pretende a Defesa, o decurso de tempo necessário à extinção da punibilidade seria desproporcional ao total de pena obtido do concurso de crimes.5. Habeas corpus denegado. (STJ, HC 92069 / RO HABEAS CORPUS 2007/0236368-6. 2010)
Ademais, enquanto não decorrido o prazo prescricional da primeira pretensão executória, a segunda pena terá sua execução suspensa durante esse lapso. Nessa linha, o STJ:

CRIMINAL. RHC. PRESCRIÇÃO EXECUTÓRIA. FUGA DO CONDENADO. CÁLCULO. ARTS. 112, II, E 113 DO CP. ACRÉSCIMO DA REINCIDÊNCIA. MAIS DE UMA CONDENAÇÃO. ORDEM DE EXECUÇÃO. PRESCRIÇÃO INOCORRENTE. RECURSO DESPROVIDO. I. Na hipótese de fuga do condenado ou de revogação da liberdade condicional, a prescrição da pretensão executória é calculada pelo resto da pena a ser cumprida, contando-se do dia em que a execução da sentença é interrompida, nos termos do art. 113 e 112, inc. II, do Código Penal. (…) III. Tratando-se de concurso material, as condenações não são somadas, mas, ao contrário, procede-se à execução das penas graves em 1º lugar. IV. Inocorre a prescrição se ainda não consumado o lapso prescricional da pretensão executória do restante da pena reclusiva, assim como da detentiva – que será executada após o cumprimento da mais grave, ficando com a execução suspensa nesse ínterim. V. Recurso desprovido. (RHC 9.158/SP, Rel. Ministro GILSON DIPP, QUINTA TURMA, julgado em 16/12/1999, DJ 28/02/2000, p. 94)

No caso, foi o réu, então primário e maior de 21 anos, condenado a uma pena de 05 (cinco) anos e 03 (três) meses pelo crime de adulteração de sinal de veículo automotor e outra de 04 (quatro) anos por receptação qualificada.
Relativamente à condenação correspondente ao crime mais grave – cujo cumprimento, portanto, deve dar-se em primeiro lugar, observo ter sido aplicada causa de aumento de pena pelo crime continuado de adulteração de sinal de veículo automotor. Portanto, tal acréscimo não deverá ser considerado para análise da prescrição executória, consoante a súmula 497 do STF: “Quando se tratar de crime continuado, a prescrição regula-se pela pena imposta na sentença, não se computando o acréscimo decorrente da continuação.”
Desse modo, considerando a pena imposta de 04 (quatro) anos, o sentenciado cumpriu 01 (um) ano, 06 (seis) meses e 24 (vinte e quatro) dias da reprimenda, restando-lhe cumprir 02 (dois) anos, 05 (cinco) meses e 06 (seis) dias, incidindo, assim, a pretensão executória de oito anos (Código Penal, arts. 109, IV).
Portanto, posto a sentença haver transitado em julgado em 11/07/2007, a prescrição começa a correr nesta data (art. 112, I, do CP); e sendo o prazo aplicável de oito anos, depreende-se que este decorreu em 10/07/2015, impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão punitiva executória.
Por conseguinte, quanto à pena de 04 (quatro) anos pelo crime de receptação, tendo sido o seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, que se deu em 10/07/2015, entende-se que esta data será o parâmetro de cálculo. Assim, incidirá a pretensão executória de oito anos (art. 109, IV, do CP), a qual será materializar-se-á apenas em 09/07/2023.
Isto posto, posto não ultrapassado o prazo prescricional, indefiro a pedido de reconhecimento da prescrição quanto à pena pelo delito cominado no art. 180, §1º, do Código Penal.
Em sequência, declaro prescrita a pretensão executória da pena privativa de liberdade executada neste autos quanto à pena do crime capitulado no art. 311, do Código Penal, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, IV e 112, I, todos do Código Penal.
P.R.I. À Secretaria, para que expeça, com urgência, mandado de prisão atualizado, com a correta validade para expiração, após o que deve-se aguardar o seu cumprimento.`,
    },
    {
        id: 'old_prescri__o___fuga___maior_de_21a___prim_rio__1__odt',
        nome: 'PRESCRIÇÃO - Fuga - Maior de 21a - Primário (1)',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO – MAIOR DE 21 E PRIMÁRIO
	Vistos etc.
Tratam os autos de processo de execução de pena imposta de sete anos e nove meses de reclusão, em regime fechado, constando certidão nos autos informando a fuga do apenado desde 27/08/2007 (ev. 1.1, fl. 74).
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (ev. 10.1).Relatados.Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.No caso, foi o réu, então primário, condenado a seis anos de reclusão, restando-lhe cumprir seis anos e vinte e nove dias de privação de liberdade, prazo este sobre o qual a pretensão executória de doze anos deve incidir (Código Penal, art. 109, III).Logo, aqui o prazo prescricional aplicável é de doze anos, já transcorrido desde 26/08/2019, posto datar a fuga do apenado em 27/08/2007, incluindo-se aí o dia do início e excluindo-se o dia do fim, por se tratar de prazo material (art. 10 do CP), impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão executória, segundo o art. 107, IV, do Código Penal.Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada neste autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, III, 110 e 112, todos do Código Penal.P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.`,
    },
    {
        id: 'old_prescri__o___fuga___maior_de_21a___prim_rio__2__odt',
        nome: 'PRESCRIÇÃO - Fuga - Maior de 21a - Primário (2)',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO – MAIOR DE 21 E PRIMÁRIO
Tratam os autos de processo de execução de pena de 06 (seis) anos e 08 (oito) meses de reclusão em regime semiaberto, pela prática de delito capitulado no  art. 157, §2º, I, do Código Penal.
A sentença condenatória data de 30/05/2006, transitada em julgado para ambas as partes em 10/07/2006, tendo o apenado foragido em 26/03/2007 (ev. 1.1, fl. 70, pv. 89).
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (9.1).
Relatório prescricional ao evento 6.1 e certidão ao evento 3.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória,  disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão. Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
No caso, foi o réu, então primário, condenado a  06 (seis) anos e 08 (oito) meses anos de reclusão, restando-lhe cumprir 04(quatro) anos e 09 (nove) meses de privação de liberdade, incidindo, assim, a pretensão executória de doze anos, posto datar a fuga de 26/03/2007 (Cód.Penal, arts. 109, III, c/c 112, II).
Portanto, sendo o prazo aplicável de doze anos, depreende-se que decorreu em 25/03/2019, impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão punitiva executória.
Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada nestes autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, III, 110 e 112, II, todos do Código Penal.
P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.

RASCUNHO

Tratam os autos de processo de execução de pena de 01 (um) ano e 09 (nove) meses de reclusão, em regime semiaberto, pela prática de delito capitulado no art. 15 da Lei 10.826/03.
A sentença condenatória data de 06/08/2009, transitada em julgado para ambas as partes em 17/08/2009, estando o apenado foragido desde 23/01/2016 (ev. 1.1, pv. 87).
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (5.1).
Certidão ao evento 2.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória,  disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão. Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
No caso, foi o réu, então primário, condenado a 01 (um) ano e 09 (nove) meses de reclusão, restando-lhe cumprir 10 (dez) dias de privação de liberdade, incidindo, assim, a pretensão executória de três anos, posto datar a fuga de 23/01/2016 (Cód. Penal, arts. 109, VI, c/c 112, II).
Portanto, sendo o prazo aplicável de três anos, depreende-se que decorreu em 22/01/2019, impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão executória.
Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada nestes autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, VI, 110 e 112, II, todos do Código Penal.
P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.`,
    },
    {
        id: 'old_prescri__o___fuga___menor_de_21a___prim_rio_odt',
        nome: 'PRESCRIÇÃO - Fuga - Menor de 21a - Primário',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO FUGA – MENOR DE 21 - PRIMÁRIO
Vistos etc.
Tratam os autos de processo de execução de pena imposta a WELTON JHONE DOS SANTOS, menor de vinte e um anos à época do fato criminoso, condenado a 06 (seis) anos, 02 (dois) meses e 20 (vinte) dias de reclusão.
A sentença condenatória data de 01/06/2012, tendo transitado em julgado em 13/07/2012.
Informam os autos a fuga do apenado desde 05/10/2014 (ev. 1.1, fl. 124, pv. 122).
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (ev. 7.1).
Anoto constar certidão ao evento 4.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
No caso, foi o réu, então primário e menor de vinte e um anos, condenado a 06 (seis) anos, 02 (dois) meses e 20 (vinte) dias de reclusão, restando-lhe cumprir 03 (três) anos, 07 (sete) meses e 01 (um) dia de privação de liberdade, prazo este sobre o qual a prescrição executória de oito deve incidir (Código Penal, arts. 109, IV).
Na hipótese, contudo, tratando-se de acusado menor de 21 anos na data do fato, incide o disposto no art. 115 do CP: "São reduzidos de metade os prazos de prescrição quando o criminoso era, ao tempo do crime, menor de 21 (vinte e um) anos, ou, na data da sentença, maior de 70 (setenta) anos".
Logo, aqui o prazo prescricional aplicável é de dois anos, já transcorrido desde 04/10/2018, posto datar a fuga do apenado em 05/10/2014, incluindo-se aí o dia do início e excluindo-se o dia do fim, por se tratar de prazo material (art. 10 do CP), impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão executória, segundo o art. 107, IV, do Código Penal.Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada nestes autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, IV, 110 e 115, todos do Código Penal.P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.

RASCUNHO

Vistos etc.
Tratam os autos de processo de execução de pena imposta a ERINALDO DOS SANTOS FERREIRA, menor de vinte e um anos à época do fato criminoso, condenado a 20 (vinte) anos de reclusão.
A sentença condenatória data de 13/04/1998, tendo transitado em julgado em 03/11/1999.
Informam os autos a fuga do apenado desde 24/04/1998, anteriormente ao trânsito em julgado da sentença condenatória (ev. 1.1, pv. 33).
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (ev. 6.1).
Anoto constar certidão ao evento 3.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
No caso, foi o réu, então primário e menor de vinte e um anos, condenado a 20 (vinte) anos de reclusão, restando-lhe cumprir 18 (dezoito) anos, 02 (dois) meses e 12 (doze) dias de privação de liberdade, prazo este sobre o qual a prescrição executória de vinte anos deve incidir (Código Penal, arts. 109, I).
Na hipótese, contudo, tratando-se de acusado menor de 21 anos na data do fato, incide o disposto no art. 115 do CP: “São reduzidos de metade os prazos de prescrição quando o criminoso era, ao tempo do crime, menor de 21 (vinte e um) anos, ou, na data da sentença, maior de 70 (setenta) anos”.
Logo, aqui o prazo prescricional aplicável é de dez anos, já transcorrido desde 02/11/2009, cujo parâmetro de cálculo é o trânsito em julgado da condenação, datada de 03/11/1999 (art. 112, I, do CP), incluindo-se aí o dia do início e excluindo-se o dia do fim, por se tratar de prazo material (art. 10 do CP), impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão executória, segundo o art. 107, IV, do Código Penal.Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada nestes autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, I, e 115, todos do Código Penal.P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.`,
    },
    {
        id: 'old_prescri__o___fuga___unifica__o___6_processos_odt',
        nome: 'PRESCRIÇÃO - Fuga - Unificação - 6 processos',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `UNIFICAÇÃO – EXTINÇÃO DE 3 PROCESSOs - PRESCRIÇÃO DE UM PROCESSO – CONTINUAÇÃO DOS OUTROS – (6 PROCESSOS)
Vistos etc.
Tratam os autos de processo de execução de pena unificada de 15 (quinze) anos, 09 (nove) meses e 10 (dez) dias de reclusão, em regime fechado.
A sentença condenatória da ação penal nº 0013635-82.2001.8.20.0001 (evento 1.1) data de 06/03/2003, transitada em julgado para ambas as partes em 13/06/2003, por delito de furto; a sentença da ação penal nº 0002624-22.2002.8.20.000 (evento 1.2) foi prolatada em 23/07/2003, tendo transitado em julgado para ambas as partes em 25/08/2003, condenado o apenado por furto; a sentença da ação penal nº 0000233-91.2002.8.20.0002 (evento 1.4) foi prolatada em 30/06/2003, tendo transitado em julgado para ambas as partes em 03/09/2003, por crime de furto qualificado; enquanto que a sentença da ação penal nº 0000278-95.2002.8.20.0002 (evento 1.3) foi prolatada em 25/09/2003, tendo transitado em julgado para ambas as partes em 12/12/2003, por furto qualificado; bem como que a sentença da ação penal nº 0000198-32.2005.8.20.0001 (evento 1.5) foi prolatada em 19/09/2006, tendo transitado em julgado para ambas as partes em 29/10/2007, por delito furto; e a sentença da ação penal nº 0024221-37.2008.8.20.0001 (evento 1.6) data de 19/12/2008, com trânsito em julgado em 03/02/2009, por crime de roubo.
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (11.1).
Certidão ao evento 8.1 esclarecendo que não existem registros de novas prisões, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Ofício oriundo da COEAP/SEAP (evento 14.1) aclarando que em 26/10/2010 o apenado fora inserido no regime semiaberto, por força de decisão de progressão de regime, não retornando ao cumprimento de pena, sendo considerado, então, foragido.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória,  disciplinada no art. 110 do mesmo estatuto.

Saliento que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)

Observo, que mesmo na hipótese de unificação de penas, a incidência da pretensão estatal para a execução deve ser feita isoladamente para cada crime. Nesse sentido é a jurisprudência do Superior Tribunal de Justiça:
HABEAS CORPUS. PROCESSO PENAL. FURTO E QUADRILHA. PRESCRIÇÃO DA PRETENSÃO EXECUTÓRIA. INOCORRÊNCIA. ANÁLISE QUE DEVE OCORRER PARA CADA DELITO PRATICADO ISOLADAMENTE.1. A análise da pretensão da prescrição executória deve ser realizada para cada delito praticado isoladamente, inclusive, no caso de concurso de crimes.2. O art. 109, do Código Penal, em seu inciso IV, prescreve o prazo prescricional de 08 (oito) anos tanto para o delito de furto quanto para o de quadrilha, em face da pena concretizada a cada um dos delitos ser superior a 02 (dois) anos e não exceder a 04 (quatro)anos. Ocorre que, na hipótese, aplica-se o art. 110, do Código Penal, pois a sentença condenatória reconheceu a reincidência do Paciente, incidindo, assim, o acréscimo de 1/3 no referido prazo,resultando no prazo prescricional de 10 (dez) anos e 08 (oito) meses.3. Considerando-se como último marco interruptivo da prescrição o dia da interrupção da execução da pena do Paciente, conforme dicção do art. 112, inciso II, do Código Penal, não se caracteriza a extinção da punibilidade pela prescrição da pretensão executória em relação ao crime de quadrilha, uma vez que não transcorreu o lapso temporal superior a 10 (dez) anos e 08 (oito) meses desde o último marco interruptivo.4. Caso se aplique, simultaneamente, o mesmo prazo de prescrição em ambas as penas, como pretende a Defesa, o decurso de tempo necessário à extinção da punibilidade seria desproporcional ao total de pena obtido do concurso de crimes.5. Habeas corpus denegado. (STJ, HC 92069 / RO HABEAS CORPUS 2007/0236368-6 . 2010)
Ademais, enquanto não decorrido o prazo prescricional da primeira pretensão executória, a segunda pena terá sua execução suspensa durante esse lapso. Nessa linha, o STJ:

CRIMINAL. RHC. PRESCRIÇÃO EXECUTÓRIA. FUGA DO CONDENADO. CÁLCULO. ARTS. 112, II, E 113 DO CP. ACRÉSCIMO DA REINCIDÊNCIA. MAIS DE UMA CONDENAÇÃO. ORDEM DE EXECUÇÃO. PRESCRIÇÃO INOCORRENTE. RECURSO DESPROVIDO. I. Na hipótese de fuga do condenado ou de revogação da liberdade condicional, a prescrição da pretensão executória é calculada pelo resto da pena a ser cumprida, contando-se do dia em que a execução da sentença é interrompida, nos termos do art. 113 e 112, inc. II, do Código Penal. (…) III. Tratando-se de concurso material, as condenações não são somadas, mas, ao contrário, procede-se à execução das penas graves em 1º lugar. IV. Inocorre a prescrição se ainda não consumado o lapso prescricional da pretensão executória do restante da pena reclusiva, assim como da detentiva – que será executada após o cumprimento da mais grave, ficando com a execução suspensa nesse ínterim. V. Recurso desprovido. (RHC 9.158/SP, Rel. Ministro GILSON DIPP, QUINTA TURMA, julgado em 16/12/1999, DJ 28/02/2000, p. 94)
De antemão, verifico que, até a data da fuga, o apenado cumpriu 08 (oito) anos e 06 (seis) meses da reprimenda. Assim, as penas impostas nos processos nº 0013635-82.2001.8.20.0001, de 01 (um) ano e 08 (oito) meses de reclusão, nº 0002624-22.2002.8.20.000, de 01 (um) ano e 06 (seis) meses de reclusão e nº 0000233-91.2002.8.20.0002, de 02 (dois) anos e 06 (seis) meses de reclusão estão totalmente cumpridas.
Desse modo, cumpridas as penas impostas, é de se julgá-las extintas, cabendo a dispensa do pagamento das custas processuais se pobre o apenado.
Tendo sido verificada a extinção de punibilidade pelo cumprimento das penas acima referenciadas, passo à análise do processo nº 0000278-95.2002.8.20.0002, cuja pena é de 04 (quatro) anos de reclusão.
Anoto que o parâmetro utilizado para análise da prescrição da pretensão executória é a data em que o apenado empreendeu fuga do estabelecimento prisional, no caso, 26/10/2010 (art. 112, II, CP).
Sendo o apenado reincidente e menor de 21 anos à época do fato, cumpriu 02 (dois) anos e 10 (dez) meses da pena imposta, resultando em uma pena remanescente de 01 (um) ano e 02 (dois) meses; sendo, assim, reconhecida a prescrição executória com o decurso de quatro anos (art. 109, VI do CP). Na hipótese, contudo, tratando-se de acusado menor de 21 anos na data do fato, incide o disposto no art. 115 do CP: “São reduzidos de metade os prazos de prescrição quando o criminoso era, ao tempo do crime, menor de 21 (vinte e um) anos, ou, na data da sentença, maior de 70 (setenta) anos”, resultando em um prazo de dois anos.
Entretanto, o referido prazo deve ser majorado em 1/3 (um terço), em virtude da reincidência do apenado, conforme disciplina o art. 110, "caput", do CP, totalizando, assim, dois anos e oito meses, ultrapassados em 25/03/2013.
Por conseguinte, quanto à quinta condenação (processo nº 0000198-32.2005.8.20.0001), o apenado era maior de 21 anos à época do fato delituoso, tendo sido o seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, que se deu em 25/03/2013, entende-se que esta data será o parâmetro de cálculo. Assim, tendo sido imposta uma pena de 01 (um) ano, 01 (um) mês e 10 (dez) dias, incidirá a pretensão executória de quatro anos (art. 109, V, do CP). Entretanto, o referido prazo deve ser majorado em 1/3 (um terço), em virtude da reincidência da apenada, conforme disciplina o art. 110, "caput", do CP, totalizando, assim, um ínterim cinco anos e quatro meses, o qual irá transcorreu em 24/07/2018.
Consequentemente, relativamente à sexta condenação (processo nº 0024221-37.2008.8.20.0001), cuja pena teve seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, que se deu em 24/07/2018, esta data será o parâmetro de cálculo. Assim, tendo sido imposta uma pena de 05 (cinco) anos, incidirá a pretensão executória de doze anos (art. 109, III, do CP). Entretanto, o referido prazo deve ser majorado em 1/3 (um terço), em virtude da reincidência da apenada, conforme disciplina o art. 110, "caput", do CP, totalizando, assim, um ínterim dezesseis meses, o qual irá transcorrer-se apenas em 23/07/2034.
Isto posto, julgo extintas, pelo cumprimento, as penas privativas de liberdade que se executavam nos processos nº 0013635-82.2001.8.20.0001, de 01 (um) ano e 08 (oito) meses de reclusão, nº 0002624-22.2002.8.20.000, de 01 (um) ano e 06 (seis) meses de reclusão e nº 0000233-91.2002.8.20.0002 e de 02 (dois) anos e 06 (seis) meses de reclusão; declaro prescritas as pretensões executórias das penas privativas de liberdade quanto aos processos nº 0000278-95.2002.8.20.0002 e nº 0000198-32.2005.8.20.0001, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, V, 110 e 112, II, todos do Código Penal e, por fim, deixo de declarar a extinção da punibilidade pela prescrição executória quanto ao processo nº 0024221-37.2008.8.20.0001, haja vista não ter transcorrido o prazo.
P.R.I. À Secretaria, para que providencie o arquivamento dos processos extintos pelo cumprimento e pela prescrição da pretensão executória, com "baixa" no SAJ e BNMP; e expeça mandado de prisão com validade atualizada.`,
    },
    {
        id: 'old_prescri__o___nunca_iniciou___medida_de_seguran_a_odt',
        nome: 'PRESCRIÇÃO - Nunca iniciou - Medida de Segurança',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO – NUNCA INICIOU – MEDIDA DE SEGURANÇA
Trata-se de execução de medida de segurança detentiva aplicada a FAUSTO VIANA PEREIRA, em razão de crime previsto no art. 157, §2º, I e II do Código Penal.
A sentença condenatória foi prolata na data de 30/09/1998, com trânsito em julgado em 19/10/1998, nunca tendo sido internado o inimputável para início do cumprimento.
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (7.1).
Certidão ao evento 4.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória,  disciplinada no art. 110 do mesmo estatuto.

Saliento que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
O STJ consolidou entendimento no sentido de que a prescrição da pretensão executória da sentença absolutória imprópria deve ser regulada pela pena em abstrato: 
DECISÃO: (…) O Superior Tribunal de Justiça já assentou a orientação de que o prazo para o cômputo da prescrição da medida de segurança aplicada ao inimputável regula-se pelo máximo da pena privativa de liberdade cominada ao crime, observados os interregnos estipulados no art. 109 do Código Penal. Nesse sentido: RECURSO ORDINÁRIO EM HABEAS CORPUS. FURTO QUALIFICADO. INIMPUTÁVEL. PRESCRIÇÃO DA MEDIDA DE SEGURANÇA. INOCORRÊNCIA. PRAZO REGULADO PELA PENA MÁXIMA EM ABSTRATO COMINADA AO CRIME. PEDIDO ALTERNATIVO PREJUDICADO. 1. A contagem do prazo para a prescrição da medida de segurança aplicada ao inimputável regula-se pelo máximo da pena provativa de liberdade cominada ao crime, nos lapsos previstos no artigo 109 do Código Penal. (…) (STJ – REsp: 1705673 SP 2017/0273247-0, Relator: Ministro ANTONIO SALDANHA PALHEIRO, Data de Publicação: DJ 01/02/2018)
No caso, foi proferida sentença absolutória imprópria, aplicando ao paciente medida de segurança detentiva, consistente em internação, pelo prazo mínimo de 01 (um) ano, sendo absolvido da prática do roubo duplamente circunstanciado. 
Assim, o máximo da pena em abstrato imposta ao crime de roubo é de dez anos, majorado de metade em decorrência da violência e ameaça exercida pelo uso de arma de fogo e em concurso de pessoas, resulta em quinze anos, incidindo o prazo prescricional de vinte anos (art. 109, I, do CP).
Sendo o prazo prescricional de vinte anos, cujo parâmetro de contagem é a data do trânsito em julgado da sentença (art. 112, I, CP), depreende-se que foi ultrapassado em 18/10/2018.
Desta forma, deve ser declarada extinta a medida de segurança em execução, em virtude de ultrapassado o limite máximo da pena abstratamente cominada ao crime correspondente à infração por ele praticada.
Isto posto, acolho o parecer ministerial e declaro extinta a medida de segurança que era executada nestes autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, I e112, I, todos do Código Penal.
P.R.I., arquivem-se os autos após o trânsito em julgado.`,
    },
    {
        id: 'old_prescri__o___nunca_iniciou___prim_rio___maior_de_21a_odt',
        nome: 'PRESCRIÇÃO - Nunca iniciou - Primário - Maior de 21a',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO – NUNCA INICIOU
Tratam os autos de processo de execução de pena imposta de 02 (dois) meses de detenção, em regime aberto, pela prática do delito capitulado no art. 147 do Código Penal.
A sentença condenatória data de 23/03/2016, transitada em julgado para ambas as partes em 04/04/2016, não tendo sido preso o apenado para iniciar o cumprimento da reprimenda.
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (12.1).
Consta certidão ao evento 9.1 esclarecendo que não existem registros de novas prisões, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória,  disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão> Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
No caso, foi o réu, então primário e maior de 21 anos, condenado a 02 (dois) meses de detenção, incidindo, assim, a pretensão executória de três anos (art. 109, VI, do CP).
Portanto, sendo o prazo aplicável de três anos, depreende-se que este decorreu em 03/04/2019, cujo parâmetro de cálculo é o trânsito em julgado da condenação, datada de 04/04/2016 (art. 112, I, do CP), impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão punitiva executória.
Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada neste autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, VI, 110 e 115, todos do Código Penal.
P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.

Vistos etc.
Tratam os autos de processo de execução de pena de XX de reclusão, em regime XX, pela prática do delito capitulado no art. XX.
A sentença condenatória data de XX, transitada em julgado para ambas as partes em XX, não tendo sido preso o apenado para iniciar o cumprimento da reprimenda.
Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (evento).
Consta certidão ao evento XX esclarecendo que não existem registros de novas prisões, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão> Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
No caso, foi o réu, então primário e maior de 21 anos, condenado a XX de reclusão, incidindo, assim, a pretensão executória de XX anos (art. 109, **, do CP).
Portanto, sendo o prazo aplicável de XX anos, depreende-se que este decorreu em XX, cujo parâmetro de cálculo é o trânsito em julgado da condenação, datada de XX (art. 112, I, do CP), impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão punitiva executória.
Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade executada neste autos, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, **, 110 e 115, todos do Código Penal.
P.R.I. Arquivem-se estes autos após o trânsito em julgado, com "baixa" no SAJ e BNMP.`,
    },
    {
        id: 'old_prescri__o___unifica__o___continuidade_delitiva_odt',
        nome: 'PRESCRIÇÃO - Unificação - Continuidade delitiva',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `PRESCRIÇÃO – UNIDICAÇÃO– CONTINUIDADE DELITIVA

Vistos etc.
Tratam os autos de processo de execução de pena unificada de 11 (onze) anos de reclusão, em regime fechado, tendo o apenado empreendido fuga do estabelecimento prisional em 11/07/2008 (evento 1.1, pv. 79).
A sentença condenatória do primeiro processo (nº 0002178-11.2005.8.20.0002) data de 10/08/2006, por delitos de roubo e porte ilegal de arma de fogo de uso permitido, transitada em julgado para ambas as partes em 25/09/2006; enquanto que a sentença do segundo processo (nº 0000329-04.2005.8.20.0002) foi prolatada em 25/10/2006, por crime capitulado no do art. 14, da Lei 10.826/2006, tendo transitado em julgado para ambas as partes em 06/08/2007.
Relatados.
Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão. Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)
Observo, contudo, que mesmo na hipótese de concurso material de crimes, a incidência da pretensão estatal para a execução deve ser feita isoladamente para cada crime, conforme preceitua o art. 119, do CP. Nesse sentido é a jurisprudência do Superior Tribunal de Justiça:
HABEAS CORPUS. PROCESSO PENAL. FURTO E QUADRILHA. PRESCRIÇÃO DA PRETENSÃO EXECUTÓRIA. INOCORRÊNCIA. ANÁLISE QUE DEVE OCORRER PARA CADA DELITO PRATICADO ISOLADAMENTE.1. A análise da pretensão da prescrição executória deve ser realizada para cada delito praticado isoladamente, inclusive, no caso de concurso de crimes. 2. O art. 109, do Código Penal, em seu inciso IV, prescreve o prazo prescricional de 08 (oito) anos tanto para o delito de furto quanto para o de quadrilha, em face da pena concretizada a cada um dos delitos ser superior a 02 (dois) anos e não exceder a 04 (quatro)anos. Ocorre que, na hipótese, aplica-se o art. 110, do Código Penal, pois a sentença condenatória reconheceu a reincidência do Paciente, incidindo, assim, o acréscimo de 1/3 no referido prazo,resultando no prazo prescricional de 10 (dez) anos e 08 (oito) meses.3. Considerando-se como último marco interruptivo da prescrição o dia da interrupção da execução da pena do Paciente, conforme dicção do art. 112, inciso II, do Código Penal, não se caracteriza a extinção da punibilidade pela prescrição da pretensão executória em relação ao crime de quadrilha, uma vez que não transcorreu o lapso temporal superior a 10 (dez) anos e 08 (oito) meses desde o último marco interruptivo.4. Caso se aplique, simultaneamente, o mesmo prazo de prescrição em ambas as penas, como pretende a Defesa, o decurso de tempo necessário à extinção da punibilidade seria desproporcional ao total de pena obtido do concurso de crimes.5. Habeas corpus denegado. (STJ, HC 92069 / RO HABEAS CORPUS 2007/0236368-6. 2010)
Ademais, enquanto não decorrido o prazo prescricional da primeira pretensão executória, a segunda pena terá sua execução suspensa durante esse lapso. Nessa linha, o STJ:

CRIMINAL. RHC. PRESCRIÇÃO EXECUTÓRIA. FUGA DO CONDENADO. CÁLCULO. ARTS. 112, II, E 113 DO CP. ACRÉSCIMO DA REINCIDÊNCIA. MAIS DE UMA CONDENAÇÃO. ORDEM DE EXECUÇÃO. PRESCRIÇÃO INOCORRENTE. RECURSO DESPROVIDO. I. Na hipótese de fuga do condenado ou de revogação da liberdade condicional, a prescrição da pretensão executória é calculada pelo resto da pena a ser cumprida, contando-se do dia em que a execução da sentença é interrompida, nos termos do art. 113 e 112, inc. II, do Código Penal. (…) III. Tratando-se de concurso material, as condenações não são somadas, mas, ao contrário, procede-se à execução das penas graves em 1º lugar. IV. Inocorre a prescrição se ainda não consumado o lapso prescricional da pretensão executória do restante da pena reclusiva, assim como da detentiva – que será executada após o cumprimento da mais grave, ficando com a execução suspensa nesse ínterim. V. Recurso desprovido. (RHC 9.158/SP, Rel. Ministro GILSON DIPP, QUINTA TURMA, julgado em 16/12/1999, DJ 28/02/2000, p. 94)

No caso, relativamente à primeira condenação (processo nº 0002178-11.2005.8.20.0002), foi o réu, então primário e maior de 21 anos, condenado a uma pena de 08 (oito) anos e 08 (oito) meses de reclusão, sendo uma pena de 06 (seis) anos e 08 (oito) meses por crime de roubo e outra de 02 (dois) anos por porte ilegal de arma.
Relativamente à condenação correspondente ao crime mais grave – cujo cumprimento, portanto, deve dar-se em primeiro lugar, observo ter sido aplicada causa de aumento de pena em ¼ (um quarto) pelo crime continuado de roubo. Portanto, tal acréscimo não deverá ser considerado para análise da prescrição executória, consoante a súmula 497 do STF: “Quando se tratar de crime continuado, a prescrição regula-se pela pena imposta na sentença, não se computando o acréscimo decorrente da continuação.”
Desse modo, considerando a pena de 05 (cinco) anos e 04 (quatro) meses, o sentenciado cumpriu 02 (dois) anos, 08 (oito) meses e 01 (um) dia da reprimenda, restando-lhe cumprir 02 (dois) anos, 07 (sete) meses e 29 (vinte e nove) dias, incidindo, assim, a pretensão executória de oito anos (Código Penal, arts. 109, IV).
Portanto, posto o apenado haver foragido em 11/07/2008 (art. 112, II, do CP); e sendo o prazo aplicável de oito anos, depreende-se que este decorreu em 10/07/2016, impondo-se o reconhecimento da extinção da punibilidade pela prescrição da pretensão punitiva executória pelo delito de roubo.
Por conseguinte, quanto à pena de 02 (dois) anos por crime de porte ilegal de arma de fogo, tendo sido o seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, que se deu em 10/07/2016, entende-se que esta data será o parâmetro de cálculo. Assim, incidirá a pretensão executória de quatro anos (art. 109, V, do CP), a qual será materializar-se-á apenas em 09/07/2020.
Consequentemente, relativamente à segunda condenação (processo nº 0000329-04.2005.8.20.0002), cuja pena teve seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, a qual se dará em 09/07/2020, esta data será o parâmetro de cálculo. Assim, considerando a pena de 02 (dois) anos e 04 (quatro) meses, incidirá a pretensão executória de oito anos (art. 109, IV, do CP). Na hipótese, contudo, tratando-se de acusado menor de 21 anos na data do fato, incide o disposto no art. 115 do CP: "São reduzidos de metade os prazos de prescrição quando o criminoso era, ao tempo do crime, menor de 21 (vinte e um) anos, ou, na data da sentença, maior de 70 (setenta) anos", alcançando-se um prazo de quatro anos, que será transcorrido somente em 08/07/2024.
Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade quanto à pena do crime capitulado no art. 157, §2º, I e II do processo nº 0002178-11.2005.8.20.0002, do Código Penal, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, IV e 112, II, todos do Código Penal; e deixo de declarar a extinção da punibilidade pela prescrição executória quanto à pena do delito capitulado no art. 14 da Lei 10.826/2003 no processo nº 0002178-11.2005.8.20.0002 bem como quanto ao processo nº 0000329-04.2005.8.20.0002, haja vista não terem sido transcorridos os prazos.
P.R.I. À Secretaria, para proceder à anotação no SEEU quanto à prescrição executória da pena relativa ao delito de roubo no processo nº 0002178-11.2005.8.20.0002; bem como para que expeça, com urgência, mandado de prisão atualizado, com a correta validade para expiração, após o que deve-se aguardar o seu cumprimento.`,
    },
    {
        id: 'old_prescri__o___unifica__o___prescri__o_de_um_processo___continua__o_do_outro_odt',
        nome: 'PRESCRIÇÃO - Unificação - Prescrição de um processo - Continuação do outro',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'prescricao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `UNIFICAÇÃO – PRESCRIÇÃO DE UM PROCESSO – CONTINUAÇÃO DO OUTRO

Tratam os autos de processo de execução de pena unificada de 09 (nove) anos e 2 (dois) meses de reclusão, em regime fechado, tendo o apenado foragido em 15/04/2007 (ev. 1.1, fl. 89, pv. 119). 
A sentença condenatória do primeiro processo (nº 0018159-54.2003.8.20.0001) data de 13/03/2005, pelo crime disposto no art. 157, §2º, I e II, do CP, transitada em julgado para ambas as partes em 22/03/2005; enquanto que a sentença do segundo processo (nº 0020445-34.2005.8.20.0001) foi prolatada em 18/09/2006, pelo crime do art. 14, da Lei 10.826/2006 c/c art. 1º da Lei 2.252/1954, tendo transitado em julgado para ambas as partes em 17/04/2009.Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (ev. 11.1).
Consta certidão ao evento 8.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0, bem como não ter sido preso em razão da ação penal nº 0106364-78.2011.8.20.0001.
Outrossim, verifico que, compulsando os autos, não foi considerada a reincidência no cadastro das ações penais, para fins de cálculos de concessão dos benefícios no SEEU.Relatados.Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)

Observo, contudo, que mesmo na hipótese de unificação de penas, a incidência da pretensão estatal para a execução deve ser feita isoladamente para cada crime. Nesse sentido é a jurisprudência do Superior Tribunal de Justiça:
HABEAS CORPUS. PROCESSO PENAL. FURTO E QUADRILHA. PRESCRIÇÃO DA PRETENSÃO EXECUTÓRIA. INOCORRÊNCIA. ANÁLISE QUE DEVE OCORRER PARA CADA DELITO PRATICADO ISOLADAMENTE.1. A análise da pretensão da prescrição executória deve ser realizada para cada delito praticado isoladamente, inclusive, no caso de concurso de crimes.2. O art. 109, do Código Penal, em seu inciso IV, prescreve o prazo prescricional de 08 (oito) anos tanto para o delito de furto quanto para o de quadrilha, em face da pena concretizada a cada um dos delitos ser superior a 02 (dois) anos e não exceder a 04 (quatro)anos. Ocorre que, na hipótese, aplica-se o art. 110, do Código Penal, pois a sentença condenatória reconheceu a reincidência do Paciente, incidindo, assim, o acréscimo de 1/3 no referido prazo,resultando no prazo prescricional de 10 (dez) anos e 08 (oito) meses.3. Considerando-se como último marco interruptivo da prescrição o dia da interrupção da execução da pena do Paciente, conforme dicção do art. 112, inciso II, do Código Penal, não se caracteriza a extinção da punibilidade pela prescrição da pretensão executória em relação ao crime de quadrilha, uma vez que não transcorreu o lapso temporal superior a 10 (dez) anos e 08 (oito) meses desde o último marco interruptivo.4. Caso se aplique, simultaneamente, o mesmo prazo de prescrição em ambas as penas, como pretende a Defesa, o decurso de tempo necessário à extinção da punibilidade seria desproporcional ao total de pena obtido do concurso de crimes.5. Habeas corpus denegado. (STJ, HC 92069 / RO HABEAS CORPUS 2007/0236368-6 . 2010)
Ademais, enquanto não decorrido o prazo prescricional da primeira pretensão executória, a segunda pena terá sua execução suspensa durante esse lapso. Nessa linha, o STJ:

CRIMINAL. RHC. PRESCRIÇÃO EXECUTÓRIA. FUGA DO CONDENADO. CÁLCULO. ARTS. 112, II, E 113 DO CP. ACRÉSCIMO DA REINCIDÊNCIA. MAIS DE UMA CONDENAÇÃO. ORDEM DE EXECUÇÃO. PRESCRIÇÃO INOCORRENTE. RECURSO DESPROVIDO. I. Na hipótese de fuga do condenado ou de revogação da liberdade condicional, a prescrição da pretensão executória é calculada pelo resto da pena a ser cumprida, contando-se do dia em que a execução da sentença é interrompida, nos termos do art. 113 e 112, inc. II, do Código Penal. (…) III. Tratando-se de concurso material, as condenações não são somadas, mas, ao contrário, procede-se à execução das penas graves em 1º lugar. IV. Inocorre a prescrição se ainda não consumado o lapso prescricional da pretensão executória do restante da pena reclusiva, assim como da detentiva – que será executada após o cumprimento da mais grave, ficando com a execução suspensa nesse ínterim. V. Recurso desprovido. (RHC 9.158/SP, Rel. Ministro GILSON DIPP, QUINTA TURMA, julgado em 16/12/1999, DJ 28/02/2000, p. 94)
Portanto, relativamente à primeira condenação (processo nº 0018159-54.2003.8.20.0001), sendo o réu maior de 21 anos à época do fato, correspondente ao crime mais grave e, portanto, o cumprimento da execução deve-se dar em primeiro lugar, a data relativa à fuga configura-se a data-base sobre a qual deve ser analisada a prescrição executória.
Desse modo, considerando a pena imposta de 06 (seis) anos e 03 (três) meses, o sentenciado cumpriu 03 (três) anos e 13 (treze) dias da reprimenda, restando-lhe cumprir 03 (três) anos, 02 (dois) meses e 17 (dezessete) dias, incidindo, assim, a pretensão executória de oito anos (Código Penal, arts. 109, IV), já transcorrida desde 14/04/2015, cujo parâmetro de cálculo é a data da fuga, qual seja, 15/04/2007 (art. 112, II, do CP).
Por conseguinte, quanto à segunda condenação (processo nº 0020445-34.2005.8.20.0001), tendo sido o seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, que se deu em 14/04/2015, entende-se que esta data será o parâmetro de cálculo. Assim, tendo sido imposta uma pena de 02 (dois) anos e 11 (onze) meses, incidirá a pretensão executória de oito anos (art. 109, IV, do CP). Entretanto, o referido prazo deve ser majorado em 1/3 (um terço), em virtude da reincidência do apenado, conforme disciplina o art. 110, "caput", do CP, totalizando, assim, um ínterim 10 (dez) anos e 08 (oito) meses anos, o qual irá transcorrer-se apenas em 13/12/2025.

Neste sentido, colhe-se da jurisprudência do Superior Tribunal de Justiça: 
"O reconhecimento da prescrição com relação às demais condenações não tem o condão de impedir o incremento do lapso prescricional, haja vista se tratar de prescrição da pretensão executória, qual não impede o reconhecimento da reincidência. (HC 354.429/RS, Rel. Ministro REYNALDO SOARES DA FONSECA, QUINTA TURMA, julgado em 14/06/2016, DJe 21/06/2016).
De fato, "o reconhecimento da prescrição da pretensão executória impossibilita o Estado de executar a pena aplicada, sem, contudo, rescindir a sentença penal condenatória, razão pela qual seus efeitos secundários - entre eles, a reincidência - permanecem inalterados". (EDcl no AgRg no AREsp 726.325/DF, Rel. Ministro ROGERIO SCHIETTI CRUZ, SEXTA TURMA, julgado em 16/02/2016, DJe 25/02/2016).
Registro, por oportuno, que "De acordo com entendimento pacificado nesta Corte Superior de Justiça, a reincidência, como causa de interrupção da prescrição da pretensão executória, é contada a partir da prática do novo delito, e não do trânsito em julgado de eventual sentença condenatória" (RHC 68.812/RJ, Rel. Ministro JORGE MUSSI, QUINTA TURMA, julgado em 05/05/2016, DJe 20/05/2016).

Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade quanto ao processo nº 0018159-54.2003.8.20.0001, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, IV, 110 e 112, II, todos do Código Penal.
Além, deixo de declarar a extinção da punibilidade pela prescrição executória quanto ao processo nº 0020445-34.2005.8.20.0001, haja vista não ter transcorrido o prazo.
À Secretaria, para que providencie o arquivamento do processo prescrito; bem como para que expeça, com urgência, mandado de prisão atualizado, com a correta validade para expiração, após o que deve-se aguardar o seu cumprimento.
P.R.I.

RASCUNHO

Tratam os autos de processo de execução de pena unificada de 06 (seis) anos e 06 (seis) meses de reclusão, em regime semiaberto, tendo o apenado foragido em 24/01/2008 (ev. 1.1, pv. 39). 
A sentença condenatória do processo nº 0025034-84.2006.8.15.0002 (evento 1.1) data de 23/10/2006, por furto qualificado, transitada em julgado para ambas as partes em 28/11/2006; enquanto que a sentença do processo nº 0023603-34.2004.8.20.0001 (evento 1.2) foi prolatada em 19/11/2007, por delito de furto qualificado, tendo transitado em julgado para ambas as partes em 16/04/2008.Interveio o Ministério Público opinando pela extinção da punibilidade em face da prescrição executória (ev. 15.1).
Consta certidão ao evento 8.1 esclarecendo que não existem registros de novas prisões após a data da fuga, conforme informações disponíveis no SEEU, SAJ-PG5 e BNMP 2.0.Relatados.Prescrição penal é a perda do poder-dever de punir do Estado pelo não exercício da pretensão punitiva ou da pretensão executória durante certo lapso de tempo, sendo a primeira, que ocorre antes de transitar em julgado a sentença, regulada pelo art. 109 do Código Penal, e a outra, que tem seu prazo em curso após o trânsito em julgado da sentença condenatória, disciplinada no art. 110 do mesmo estatuto.
Saliente-se que o trânsito em julgado a se considerar deve ser para ambas as partes, consoante entendimento do STF:
RECURSO ESPECIAL. PRERROGATIVA DE FORO. PRESCRIÇÃO. INOCORRÊNCIA. TERMO INICIAL. DEMAIS TESES RECURSAIS REJEITADAS. IMEDIATA EXECUÇÃO DA PENA. I. TERMO INICIAL DA PRETENSÃO EXECUTÓRIA. 1. A prescrição da pretensão executória pressupõe a inércia do titular do direito de punir. (...). 2. O entendimento defensivo de que a prescrição da pretensão executória se inicia com o trânsito em julgado para a acusação viola o direito fundamental à inafastabilidade da jurisdição que pressupõe a existência de uma tutela jurisdicional efetiva, ou melhor, uma justiça efetiva. (...) 4. Desse modo, se não houve ainda o trânsito em julgado para ambas as partes, não há falar-se em prescrição da pretensão executória. (...) (RE 696533, Relator (a): Min. LUIZ FUX, Relator (a) p/ Acórdão Min. ROBERTO BARROSO, Primeira Turma, julgado em 06/02/2018, PROCESSO ELETRÔNICO DJe-041 DIVULG 02-03-2018 PUBLIC 05-03-2018)

Observo, contudo, que mesmo na hipótese de unificação de penas, a incidência da pretensão estatal para a execução deve ser feita isoladamente para cada crime. Nesse sentido é a jurisprudência do Superior Tribunal de Justiça:
HABEAS CORPUS. PROCESSO PENAL. FURTO E QUADRILHA. PRESCRIÇÃO DA PRETENSÃO EXECUTÓRIA. INOCORRÊNCIA. ANÁLISE QUE DEVE OCORRER PARA CADA DELITO PRATICADO ISOLADAMENTE.1. A análise da pretensão da prescrição executória deve ser realizada para cada delito praticado isoladamente, inclusive, no caso de concurso de crimes.2. O art. 109, do Código Penal, em seu inciso IV, prescreve o prazo prescricional de 08 (oito) anos tanto para o delito de furto quanto para o de quadrilha, em face da pena concretizada a cada um dos delitos ser superior a 02 (dois) anos e não exceder a 04 (quatro)anos. Ocorre que, na hipótese, aplica-se o art. 110, do Código Penal, pois a sentença condenatória reconheceu a reincidência do Paciente, incidindo, assim, o acréscimo de 1/3 no referido prazo,resultando no prazo prescricional de 10 (dez) anos e 08 (oito) meses.3. Considerando-se como último marco interruptivo da prescrição o dia da interrupção da execução da pena do Paciente, conforme dicção do art. 112, inciso II, do Código Penal, não se caracteriza a extinção da punibilidade pela prescrição da pretensão executória em relação ao crime de quadrilha, uma vez que não transcorreu o lapso temporal superior a 10 (dez) anos e 08 (oito) meses desde o último marco interruptivo.4. Caso se aplique, simultaneamente, o mesmo prazo de prescrição em ambas as penas, como pretende a Defesa, o decurso de tempo necessário à extinção da punibilidade seria desproporcional ao total de pena obtido do concurso de crimes.5. Habeas corpus denegado. (STJ, HC 92069 / RO HABEAS CORPUS 2007/0236368-6 . 2010)
Ademais, enquanto não decorrido o prazo prescricional da primeira pretensão executória, a segunda pena terá sua execução suspensa durante esse lapso. Nessa linha, o STJ:

CRIMINAL. RHC. PRESCRIÇÃO EXECUTÓRIA. FUGA DO CONDENADO. CÁLCULO. ARTS. 112, II, E 113 DO CP. ACRÉSCIMO DA REINCIDÊNCIA. MAIS DE UMA CONDENAÇÃO. ORDEM DE EXECUÇÃO. PRESCRIÇÃO INOCORRENTE. RECURSO DESPROVIDO. I. Na hipótese de fuga do condenado ou de revogação da liberdade condicional, a prescrição da pretensão executória é calculada pelo resto da pena a ser cumprida, contando-se do dia em que a execução da sentença é interrompida, nos termos do art. 113 e 112, inc. II, do Código Penal. (…) III. Tratando-se de concurso material, as condenações não são somadas, mas, ao contrário, procede-se à execução das penas graves em 1º lugar. IV. Inocorre a prescrição se ainda não consumado o lapso prescricional da pretensão executória do restante da pena reclusiva, assim como da detentiva – que será executada após o cumprimento da mais grave, ficando com a execução suspensa nesse ínterim. V. Recurso desprovido. (RHC 9.158/SP, Rel. Ministro GILSON DIPP, QUINTA TURMA, julgado em 16/12/1999, DJ 28/02/2000, p. 94)
Portanto, relativamente processo nº 0025034-84.2006.8.15.0002 (evento 1.1), sendo o réu maior de 21 anos à época do fato e considerando a pena imposta de 03 (três) anos e 06 (seis) meses, o sentenciado cumpriu 01 (um) ano, 09 (nove) meses e 12 (doze) dias da reprimenda, restando-lhe cumprir 01 (um) ano, 08 (oito) meses e 18 (dezoito) dias, incidindo, assim, a pretensão executória de quatro anos (Código Penal, arts. 109, V), já transcorrida desde 23/01/2012, cujo parâmetro de cálculo é a data da fuga, qual seja, 24/01/2008 (art. 112, II, do CP).
Por conseguinte, quanto à segunda condenação (processo nº 0023603-34.2004.8.20.0001 – evento 1.2), tendo sido o seu cumprimento suspenso enquanto não consumado o lapso prescricional da pretensão executória anterior, que se deu em 23/01/2012, entende-se que esta data será o parâmetro de cálculo. Assim, imposta uma pena de 03 (três) anos e tendo sido o réu custodiado por 03 (três) dias, tem-se uma pena remanescente de 02 (dois) anos, 11 (onze) meses e 27 (vinte e sete) dias, sobre a qual incidirá a pretensão executória de oito anos (art. 109, IV, do CP), que será ultrapassado apenas em 22/01/2020. 

Isto posto, declaro prescrita a pretensão executória da pena privativa de liberdade quanto ao processo nº 0025034-84.2006.8.15.0002, o que faço com arrimo no art. 107, IV, 1ª parte, c/c arts. 109, V, e 112, II, todos do Código Penal; deixo de declarar a extinção da punibilidade pela prescrição executória quanto ao processo nº 0023603-34.2004.8.20.0001, haja vista não ter transcorrido o prazo.
P.R.I. À Secretaria, para que providencie o arquivamento do processo prescrito; bem como para que expeça, com urgência, mandado de prisão atualizado, com a correta validade para expiração, após o que deve-se aguardar o seu cumprimento.`,
    },
];
