// Modelos extraídos da pasta OLD - remicao
// Total: 4 modelos
// Tipos: decisao
// Formatos: ODT
// Data: 2026-01-21T00:41:14.317Z

export const MODELOS_REMICAO_OLD = [
    {
        id: 'old_decis_o_remi__o_deferido_trabalho__indeferido_estudo_odt',
        nome: 'DECISÃO REMIÇÃO DEFERIDO TRABALHO, INDEFERIDO ESTUDO',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'remicao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Vistos etc.
Trata-se de remição de parte da pena pelo estudo e trabalho, conforme relatório e declarações (ev.38/39/42 a 46/ 53 e 54).
Interveio o Ministério Público, pedindo que o apenado demonstrasse, através de documentos hábeis, a prestação dos trabalhos de
economista, e, quanto ao estudo, opinou que a contagem da remição seja feita de 1 (um) dia de pena para cada 12 (doze) horas de estudo,
bem como que se comprove que o apenado cursou algum período universitário, com os respectivos resultados, não bastando somente a
declaração de matrícula (evento 49).
Ademais, o órgão ministerial opinou que há impossibilidade de remição cumulativa de estudo e trabalho pelo período superior a 8
(oito) horas diárias (evento 49).
Relatados.
Com razão parcial o parecer, pois o apenado não comprovou idoneamente a sua frequência diária na faculdade, juntando apenas a
declaração de matrícula, com carga horária de cada matéria e a quantidade de faltas, o que não coincide com os dias peticionados (ev. 42,43
e 44), sendo assim impossível calcular os dias de estudo para remição . Já quanto a declaração de trabalho do evento 39, o apenado juntou a
declaração de trabalho, com a quantidade de horas e a frequência de cada mês, comprovando assim o tempo a remir.
Note-se, na lição do festejado Prof. Julio Fabbrini Mirabete, que “a Lei de Execução instituiu no País uma forma de redenção de
parte da pena privativa de liberdade através de remição, na qual, pelo trabalho, o condenado abrevia parte do tempo de sua condenação”.
Impende registrar que quanto a compatibilidade de remição cumulativa, só poderá ser calculada com o período de até 8 (oito) horas,
após comprovação de documentos idôneos quanto ao estudo.
Isto posto, declaro remidos da pena em execução, mandando intimar o 21 (vinte e um) dias apenado a comprovar
documentalmente a frequência diária escolar; atendido, façam-se os cálculos de acordo com a carga horária de até 8 (oito) horas com a
remição cumulativa de trabalho e estudo.
P.R.I. Insira-se o evento no SEEU, para correção dos cálculos de benefícios.`,
    },
    {
        id: 'old_remi__o_enem_odt',
        nome: 'Remição ENEM',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'remicao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `CARLA DE PAIVA UBARANA ARAÚJO LEAL, condenada a nove anos e quatro meses de reclusão em regime fechado, requereu remição de 100 dias pelo estudo, amparada na previsão do art. 126da Lei 12.433/2011 e na Recomendação nº 44/2013, do CNJ, no que acostou comprovante de aprovação e matrícula no curso de gastronomia (ev. 108).
Opinou o Ministério Público pela parcial procedência, para que fossem remidos 50 dias (ev. 118).
Relatados.
A Recomendação nº 44/2013 do CNJ indica aos Tribunais a possibilidade de remição por aprovação nos exames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM), a saber:
RECOMENDAÇÃO N. 44, DE 26 DE NOVEMBRO DE 2013. Dispõe sobre atividades educacionais complementares para fins de remição da pena pelo estudo e estabelece critérios para a admissão pela leitura. Art. 1º Recomendar aos Tribunais que: (...).
IV - na hipótese de o apenado não estar, circunstancialmente, vinculado a atividades regulares de ensino no interior do estabelecimento penal e realizar estudos por conta própria, ou com simples acompanhamento pedagógico, logrando, com isso, obter aprovação nosexames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM), a fim de se dar plena aplicação ao disposto no § 5º do art. 126 da LEP (Lei n. 7.210/84), considerar, como base de cálculo para fins de cômputo das horas,visando à remição da pena pelo estudo, 50% (cinquenta por cento) da carga horária definida legalmente para cada nível de ensino [fundamental ou médio - art. 4º, incisos II, III e seu parágrafo único, todos da Resolução n. 03/2010, do CNE], isto é, 1600 (mil e seiscentas)horas para os anos finais do ensino fundamental e 1200 (mil e duzentas) horas para o ensino médio ou educação profissional técnica de nível médio; […]
Como resultado de uma interpretação analógica in bonam partem da norma inserta no art. 126 da LEP, segundo reiterada jurisprudência do Superior Tribunal de Justiça, é possível a hipótese de abreviação da reprimenda em razão de atividades que não estejam expressas no texto legal. Neste sentido,os seguintes precedentes:
EXECUÇÃO PENAL. HABEAS CORPUS SUBSTITUTIVO DE RECURSO PRÓPRIO. REMIÇÃO DA PENA. ART. 126 DA LEI N. 7.210/1984. EXECUÇÃO PENAL. RECOMENDAÇÃO N. 44/2013 DO CNJ. APROVAÇÃO NO ENEM E NO ENCCEJA. APENADO VINCULADO A ATIVIDADES REGULARES DE ENSINO NO INTERIOR DO ESTABELECIMENTO PRISIONAL. INTERPRETAÇÃO EXTENSIVA IN BONAM PARTEM. POSSIBILIDADE. MANIFESTA ILEGALIDADE VERIFICADA. WRIT NÃO CONHECIDO. ORDEM CONCEDIDA, DE OFÍCIO. 1. Esta Corte e o Supremo Tribunal Federal pacificaram orientação no sentido de que não cabe habeas corpus substitutivo do 
recurso legalmente previsto para a hipótese, impondo-se o não conhecimento da impetração,salvo quando constatada a existência de flagrante ilegalidade no ato judicial impugnado, a justificar a concessão da ordem, de ofício. 2. A jurisprudência deste Superior Tribunal de Justiça, como resultado de uma interpretação analógica in bonam partem da norma inserta no art. 126 da LEP, possui entendimento de que é possível a hipótese de abreviação da reprimenda em razão de atividades que não estejam expressas no texto legal. 3. A Recomendação n. 44/2013 do CNJ indica aos Tribunais a possibilidade de remição por aprovação nos exames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM). 4. In casu, diante da possibilidade de interpretação extensiva in bonam partem, entende-se que cabe a remição até mesmo para presos que estudam por conta própria, não havendo falar em afastamento da possibilidade daconcessão da benesse aos apenados que estejam vinculados a atividades regulares de ensinono interior do estabelecimento. 5. Habeas corpus não conhecido. Ordem concedida, de ofício,para reconhecer o direito do paciente à remição da pena pela aprovação no ENCCEJA(Exame Nacional para Certificação de Competências de Jovens e Adultos) e no ENEM(Exame Nacional do Ensino Médio). (HC 361.462/DF, Rel. Ministro RIBEIRO DANTAS,QUINTA TURMA, julgado em 18/05/2017, DJe 25/05/2017).
AGRAVO REGIMENTAL NO AGRAVO EM RECURSO ESPECIAL. EXECUÇÃO PENAL. REMIÇÃO PELA LEITURA. POSSIBILIDADE. ACÓRDÃO DO TRIBUNAL DE ORIGEM EM DISSONÂNCIA COM A ORIENTAÇÃO JURISPRUDENCIAL DESTA CORTE SUPERIOR. MANUTENÇÃO DA DECISÃO AGRAVADA. INSURGÊNCIA DESPROVIDA. 1. Hipótese em que o reeducando teve remidos quatro dias de sua reprimenda privativa de liberdade pela leitura, nos termos da Recomendação n.º 44/2013, do Conselho Nacional de Justiça. 2. Esta Corte Superior de Justiça firmou entendimento no sentido de ser viável a concessão da remissão por atividades não expressas na lei, diante de uma interpretação extensiva in bonam partem do artigo 126 da Lei de Execução Penal. 3.Agravo regimental a que se nega provimento." (AgRg no AREsp 696.637/SP, Rel. Ministro JORGE MUSSI, QUINTA TURMA, julgado em 23/02/2016, DJe 04/03/2016).
HABEAS CORPUS SUBSTITUTIVO. EXECUÇÃO PENAL. (1) REMIÇÃO DA PENA PELA LEITURA. ART. 126 DA LEI DE EXECUÇÃO PENAL. TELEOLOGIA. INTERPRETAÇÃO EXTENSIVA IN BONAM PARTEM. PRECEDENTES. (2) WRIT NÃO CONHECIDO. ORDEM CONCEDIDA DE OFÍCIO. 1. A finalidade do instituto da remição, ao abreviar a pena, é incentivar o bom comportamento do sentenciado e sua readaptação ao convívio social e, portanto, o art. 126 da LEP admite interpretação extensiva in bonam partem, permitindo-se a remição pela leitura. 2. Writ não conhecido. Ordem expedida de ofício, para restabelecer a decisão do juízo singular (execução n.º 815/14). (HC326.499/SP, Rel. Ministra MARIA THEREZA DE ASSIS MOURA, SEXTA TURMA, julgado em 04/08/2015, DJe 17/08/2015.)
Assim, diante da possibilidade de interpretação extensiva in bonam partem, entende-se que cabe a remição até mesmo para presos que estudam por conta própria, não havendo se falar em afastamento da possibilidade da concessão da benesse aos apenados que estejam vinculados a atividades regulares de ensino no interior do estabelecimento. De seu lado, apesar da apenada fazer jus a remição pelo estudo de 50% (cinquenta por cento) da carga horária definida legalmente para o ensino médio, conquanto tenha, supostamente, realizado estudo por conta própria no interior do presídio, ou seja, 1.200 horas, não possui ela direito ao acréscimo previsto no § 5º do art. 126 da LEP. É que o § 5º vaticina que o tempo a remir em função das horas de estudo será acrescido de um terço no caso de conclusão do ensino fundamental, médio ou superior durante o cumprimento da pena,desde que certificada pelo órgão competente do sistema de educação. 
]No caso, a executada não concluiu ensino fundamental, médio ou superior no curso do cumprimento da pena, não importando que tenha prestado o ENEM no seu curso. Como é cediço, a apenada já tinha nível superior completo antes do início do cumprimento da reprimenda, como consta na qualificação dos seus dados pessoais inseridos neste processo. Em arremate, como a apenada foi aprovada em todas as áreas de conhecimento do ENEM,obtendo êxito para o curso de gastronomia, no qual matriculou-se, faz jus a remir 100 dias da pena e não apenas 50 como opinou o Ministério Público. Este é o entendimento do STJ:
AGRAVO REGIMENTAL NO HABEAS CORPUS. EXECUÇÃO PENAL. REMIÇÃO DA PENA PELA APROVAÇÃO NO EXAME NACIONAL DO ENSINO MÉDIO (ENEM).ART. 126 DA LEP. RECOMENDAÇÃO N. 44/2013 DO CNJ. BASE DE CÁLCULO. ARTS. 24, I, E 35 DA LEI 9.394/1996. AGRAVO REGIMENTAL NÃO PROVIDO. 1. O art. 126 da Lei de Execução Penal determina que o condenado que cumpre a pena em regime fechado ou semiaberto poderá remir, por trabalho ou por estudo, parte do tempo de execução da pena. 2. Esta Corte Superior de Justiça firmou entendimento e tem admitido a possibilidade de abreviação da reprimenda em razão de atividades que não estejam expressas no texto legal, como resultado de uma interpretação analógica in bonam partem da norma inserta no art. 126 da LEP. De outro lado, a Recomendação n. 44/2013 do CNJ indica aos Tribunais a possibilidade de remição por aprovação nos exames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM).Verifica-se, portanto, que o objetivo deste conjunto de regras acerca da remição da pena por aproveitamento dos estudos é o de incentivar os apenados aos estudos, bem como sua readaptação ao convívio social. 3. Considerando como base de cálculo 50% da carga horária definida legalmente para o ensino médio, ou seja, 1.200 horas, deve-se dividir esse total por doze, encontrando-se o resultado de 100 dias de remição em caso de aprovação em todos os campos de conhecimento do ENEM. Serão devidos, portanto, 20dias de remição para cada uma das cinco áreas de conhecimento. 4. In casu, como o agravado obteve aprovação integral, ou seja, nas cinco áreas de conhecimento, a remição deve corresponder a 100 dias com os acréscimos legalmente permitidos.. 5. Agravo regimental Interpretação dos arts. 24, I, e 35 da Lei n. 9.394/1996. Precedentes não provido.(AgRg no HC 447.375/SC, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 04/04/2019, DJe 10/04/2019).
"AGRAVO REGIMENTAL NO HABEAS CORPUS. PENAL E PROCESSUAL PENAL. REMIÇÃO DA PENA. APROVAÇÃO NO ENEM. INCENTIVO AO ESTUDO. CARÁTER DE RESSOCIALIZAÇÃO DA PENA. INTERPRETAÇÃO EXTENSIVA DO ART. 126 DA LEI DE EXECUÇÃO PENAL - LEP. POSSIBILIDADE. RECOMENDAÇÃO N. 44/2013 DO CONSELHO NACIONAL DE JUSTIÇA – CNJ. UTILIZAÇÃO. AGRAVO DESPROVIDO. 1. A jurisprudência deste Superior Tribunal de Justiça - STJ tem admitido que a norma do art. 126 da LEP, ao possibilitar a abreviação da pena, tem por objetivo a ressocialização do condenado encorajando, inclusive, como no caso concreto, seu estudo por conta própria e consequente aprovação no Exame Nacional do Ensino Médio - ENEM, sendo possível o uso da analogia in bonam partem, que admita o benefício em comento em razão de atividades que não estejam expressas no texto legal, nos termos da Recomendação n. 44/2013 do Conselho Nacional de Justiça, buscando, primordialmente, a readaptação do apenado ao convívio social. Precedentes. 2. A Resolução CNJ n. 44/2013 menciona a carga horária de 1.600 horas para o ensino fundamental, e 1.200horas para o ensino médio, que se refere ao percentual de 50% da carga horária definida legalmente para cada nível de ensino. Considerando como base de cálculo 50% da carga horária definida legalmente para o ensino médio, ou seja, 1.200 horas, deve-se dividir esse total por 12, encontrando-se o resultado de 100 dias de remição em caso de Na hipótese, como o paciente aprovação em todos os campos de conhecimento do ENEM. obteve aprovação em duas áreas de conhecimento do ENEM, a remição deve corresponder à40 dias. 3. Agravo desprovido." (AgRg no HC 464.410/SC, rel. Ministro JOEL ILANPACIORNIK, QUINTA TURMA, j. 23/10/2018, DJe 8/11/2018.)
Enfim, de acordo a documentação junta, tem-se que a executada deve ser beneficiada como se houvesse participado de 1.200 horas/aula, pelo que 100 dias da pena a ela imposta encontram-se remidos pelo estudo, haja vista a aprovação em todas as áreas de conhecimento do ENEM,nos termos da Recomendação nº 44/2013 do CNJ e dos precedentes do STJ. 
Isto posto, afasto a incidência do § 5º do art. 126 da LEP e declaro remidos três meses e dez dias da pena em execução, nos termos da Recomendação nº 44/2013 do CNJ e dos precedentes do STJ. P.R.I. Insira-se o evento no SEEU, para correção dos cálculos de benefícios. Em seguida, dê-se vista ao Ministério Público para se pronunciar acerca do pedido de indulto (ev. 125).`,
    },
    {
        id: 'old_remi__o_estudo_enem_e_ensino_superior_odt',
        nome: 'remição estudo enem e ensino superior',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'remicao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Vistos etc.
MARLOS GUSTAVOS DE CALDAS BRITO, condenado a treze anos e seis meses de reclusão, atualmente em regime semiaberto, requereu remição de 100 dias pelo estudo, amparada na previsão do art. 126 da Lei 12.433/2011 e na Recomendação nº 44/2013, do CNJ, período correspondente ao 50% da carga horária definitiva para o ensino médio em instituição de ensino e ainda requereu 49 dias em relação a carga horária de estudo no ano de 2018 em curso superior de licenciatura em informática (evento 8).
Opinou o Ministério Público pela  procedência em parte,  em razão que o apenado deve ser beneficiado como se houvesse participado de 1.200 horas/aula, devendo remir a pena em 50 (cinquenta) dias por ter sido aprovada no ENEM/2017 e 16 (dezesseis) dias em relação a carga horária de estudos em 2018 (evento 11).
Relatados.
A Recomendação nº 44/2013 do CNJ indica aos Tribunais a possibilidade de remição por aprovação nos exames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM), a saber: 
RECOMENDAÇÃO N. 44, DE 26 DE NOVEMBRO DE 2013. Dispõe sobre atividades educacionais complementares para fins de remição da pena pelo estudo e estabelece critérios para a admissão pela leitura. Art. 1º Recomendar aos Tribunais que: (...). 
IV - na hipótese de o apenado não estar, circunstancialmente, vinculado a atividades regulares de ensino no interior do estabelecimento penal e realizar estudos por conta própria, ou com simples acompanhamento pedagógico, logrando, com isso, obter aprovação nos exames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM), a fim de se dar plena aplicação ao disposto no § 5º do art. 126 da LEP (Lei n. 7.210/84), considerar, como base de cálculo para fins de cômputo das horas, visando à remição da pena pelo estudo, 50% (cinquenta por cento) da carga horária definida legalmente para cada nível de ensino [fundamental ou médio - art. 4º, incisos II, III e seu parágrafo único, todos da Resolução n. 03/2010, do CNE], isto é, 1600 (mil e seiscentas) horas para os anos finais do ensino fundamental e 1200 (mil e duzentas) horas para o ensino médio ou educação profissional técnica de nível médio; [...]

Como resultado de uma interpretação analógica in bonam partem da norma inserta no art. 126 da LEP, segundo reiterada jurisprudência do Superior Tribunal de Justiça, é possível a hipótese de abreviação da reprimenda em razão de atividades que não estejam expressas no texto legal. Neste sentido, os seguintes precedentes:

EXECUÇÃO PENAL. HABEAS CORPUS SUBSTITUTIVO DE RECURSO PRÓPRIO. REMIÇÃO DA PENA. ART. 126 DA LEI N. 7.210/1984. EXECUÇÃO PENAL. RECOMENDAÇÃO N. 44/2013 DO CNJ. APROVAÇÃO NO ENEM E NO ENCCEJA. APENADO VINCULADO A ATIVIDADES REGULARES DE ENSINO NO INTERIOR DO ESTABELECIMENTO PRISIONAL. INTERPRETAÇÃO EXTENSIVA IN BONAM PARTEM. POSSIBILIDADE. MANIFESTA ILEGALIDADE VERIFICADA. WRIT NÃO CONHECIDO. ORDEM CONCEDIDA, DE OFÍCIO. 1. Esta Corte e o Supremo Tribunal Federal pacificaram orientação no sentido de que não cabe habeas corpus substitutivo do recurso legalmente previsto para a hipótese, impondo-se o não conhecimento da impetração, salvo quando constatada a existência de flagrante ilegalidade no ato judicial impugnado, a justificar a concessão da ordem, de ofício. 2. A jurisprudência deste Superior Tribunal de Justiça, como resultado de uma interpretação analógica in bonam partem da norma inserta no art. 126 da LEP, possui entendimento de que é possível a hipótese de abreviação da reprimenda em razão de atividades que não estejam expressas no texto legal. 3. A Recomendação n. 44/2013 do CNJ indica aos Tribunais a possibilidade de remição por aprovação nos exames nacionais que certificam a conclusão do ensino fundamental Exame Nacional para Certificação de Competências de Jovens e Adultos (ENCCEJA) ou médio Exame Nacional do Ensino Médio (ENEM). 4. In casu, diante da possibilidade de interpretação extensiva in bonam partem, entende-se que cabe a remição até mesmo para presos que estudam por conta própria, não havendo falar em afastamento da possibilidade da concessão da benesse aos apenados que estejam vinculados a atividades regulares de ensino no interior do estabelecimento. 5. Habeas corpus não conhecido. Ordem concedida, de ofício, para reconhecer o direito do paciente à remição da pena pela aprovação no ENCCEJA (Exame Nacional para Certificação de Competências de Jovens e Adultos) e no ENEM (Exame Nacional do Ensino Médio). (HC 361.462/DF, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 18/05/2017, DJe 25/05/2017).

AGRAVO REGIMENTAL NO AGRAVO EM RECURSO ESPECIAL. EXECUÇÃO PENAL. REMIÇÃO PELA LEITURA. POSSIBILIDADE. ACÓRDÃO DO TRIBUNAL DE ORIGEM EM DISSONÂNCIA COM A ORIENTAÇÃO JURISPRUDENCIAL DESTA CORTE SUPERIOR. MANUTENÇÃO DA DECISÃO AGRAVADA. INSURGÊNCIA DESPROVIDA. 1. Hipótese em que o reeducando teve remidos quatro dias de sua reprimenda privativa de liberdade pela leitura, nos termos da Recomendação n.º 44/2013, do Conselho Nacional de Justiça. 2. Esta Corte Superior de Justiça firmou entendimento no sentido de ser viável a concessão da remissão por atividades não expressas na lei, diante de uma interpretação extensiva in bonam partem do artigo 126 da Lei de Execução Penal. 3. Agravo regimental a que se nega provimento." (AgRg no AREsp 696.637/SP, Rel. Ministro JORGE MUSSI, QUINTA TURMA, julgado em 23/02/2016, DJe 04/03/2016).

HABEAS CORPUS SUBSTITUTIVO. EXECUÇÃO PENAL. (1) REMIÇÃO DA PENA PELA LEITURA. ART. 126 DA LEI DE EXECUÇÃO PENAL. TELEOLOGIA. INTERPRETAÇÃO EXTENSIVA IN BONAM PARTEM. PRECEDENTES. (2) WRIT NÃO CONHECIDO. ORDEM CONCEDIDA DE OFÍCIO. 1. A finalidade do instituto da remição, ao abreviar a pena, é incentivar o bom comportamento do sentenciado e sua readaptação ao convívio social e, portanto, o art. 126 da LEP admite interpretação extensiva in bonam partem, permitindo-se a remição pela leitura. 2. Writ não conhecido. Ordem expedida de ofício, para restabelecer a decisão do juízo singular (execução n.º 815/14). (HC 326.499/SP, Rel. Ministra MARIA THEREZA DE ASSIS MOURA, SEXTA TURMA, julgado em 04/08/2015, DJe 17/08/2015.)
Assim, diante da possibilidade de interpretação extensiva in bonam partem, entende-se que cabe a remição até mesmo para presos que estudam por conta própria, não havendo se falar em afastamento da possibilidade da concessão da benesse aos apenados que estejam vinculados a atividades regulares de ensino no interior do estabelecimento. 
De logo, verifico que para os cálculos devem ser observados os termos do artigo 126 § 1º, inciso I, e § 5º, da LEP e a Recomendação nº 44/2013 do CNJ, dividindo-se o total obtido, 600 horas, por 12 (um dia de pena para cada doze horas), resultando em 50 dias de remição.
Quanto a remição pelo estudo em ensino superior, o artigo 126 da LEP dispõe que "o condenado que cumpre a pena em regime fechado ou semiaberto poderá remir, por trabalho ou por estudo, parte do tempo de execução da pena". Ademais, o artigo 126 §1º, I da Lei nº 12.433/2011, aduz que a remição pelo estudo tem como contagem de tempo a razão de a cada 12 (doze) horas de frequência escolar - atividade de ensino fundamental, médio, inclusive profissionalizante, ou superior, ou ainda de requalificação profissional - divididas, no mínimo, em 3 (três) dias.
Desse modo, é de se observar que no ano letivo de 2018, o apenado cumpriu carga horária total de 584,8 horas de estudo, sendo que a cada 12 (doze) horas, o apenado fará jus a remição de um dia de pena, que é 48 (quarenta e oito) dias, divididas, no mínimo em 3 (três) dias, ficando assim 16 (dezesseis) dias remidos da sua pena.
Isto posto, declaro remidos 2 (dois) meses e 6 (seis) dias da pena em execução, sendo 50 (cinquenta dias) remidos por ter sido aprovado no ENEM/2017, e 16 (dezesseis) dias em relação a carga horária de estudos em ensino superior no ano de 2018.`,
    },
    {
        id: 'old_remi__o__deferimento_trabalho__indeferimento_estudo_odt',
        nome: 'remição- deferimento trabalho, indeferimento estudo',
        tipoDocumento: 'decisao',
        magistrado: 'henriqueBaltazar',
        agrupador: 'remicao',
        fonteOriginal: 'OLD_ODT',
        dataExtracao: '2026-01-21',
        conteudo: `Vistos etc.
Trata-se de remição de parte da pena pelo trabalho, conforme relatório e cálculos juntos (eventos 46/49).
Anoto que a defesa também requereu remição pelo estudo, conforme relatório (evento 28.3)
Decido.
De logo esclareço, que quanto a remição pelo estudo, apenas uma declaração de matrícula do curso ou horário das aulas não
caracteriza como prova idônea para assegurar que o apenado assiste às aulas, sendo necessários documentos que comprovem sua presença,
como, por exemplo, folha de frequência.
Quanto ao trabalho, face à documentação junta se verifica que a apenado trabalhoa, efetivamente, 167 (cento e sessenta e sete) dias
pelo que 55 (cinquenta e cinco) dias da pena a ela imposta se encontram remidos pelo trabalho.
Note-se, na lição do festejado Prof. Julio Fabbrini Mirabete, que “a Lei de Execução instituiu no País uma forma de redenção de
parte da pena privativa de liberdade através de remição, na qual, pelo trabalho, o condenado abrevia parte do tempo de sua condenação”.
Isto posto, declaro remidos 55 (cinquenta e cinco) dias da pena em execução.
P.R.I. Insira-se o evento no SEEU, para correção dos cálculos de benefícios. Intime-se à defesa para que apresente provas idôneas
de que a apenada comparece às aulas para então decidir acerca da remição pelo estudo, bem como atualizem-se os cálculos da remição pelo
trabalho, já que faltam dois meses nos apresentados.`,
    },
];
